controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

custom_endpoint:
    path: /artist/{artistId}/album/{albumId}/song/{songId}
    controller: App\Controller\CustomController::customAction
    methods: [GET]
